### ISSUE TITLE
Finish organization migration

### ISSUE THREAD

**Issue by Wakeful-Cloud** [wasmerio/wapm-publish#1]
@syrusakbary I don't have access, so can you do the following:
1. Publish `v1.0.0` to GitHub marketplace (For some unknown reason the release was deleted during the transition)
2. Add WAPM credentials for testing (See [`test.yml`](https://github.com/wasmerio/wapm-publish/blob/23f32cf0bebe642424c2c18fe411ada67e65a0d3/.github/workflows/test.yml#L35))

**Comment by syrusakbary** [comment]
Just did 1.

I also added you the full rights to the repo so you can also admin. I can do `2` as well, but I want to make sure you have full access and perms to do it :)

**Comment by Wakeful-Cloud** [comment]
@syrusakbary I got the perms. It'd probably make sense to use one of Wasmer's accounts instead of mine.

**Comment by syrusakbary** [comment]
I just created the PR for using Wasmer WAPM account and the development registry #2, if you can review it would be great @Wakeful-Cloud

**Comment by Wakeful-Cloud** [comment]
Merged #2, tests passing!
