### ISSUE TITLE
Usefulness?

### ISSUE THREAD

**Issue by jcaesar** [wasmerio/wapm-publish#4]
Since wapm.io (recently?) hands out easy to use, nameable tokens, is there any advantage in using this action over just
```yaml
      - name: Setup Wasmer
        uses: wasmerio/setup-wasmer@v1
      - name: WAPM publish
        run: wapm publish
        env:
          WAPM_REGISTRY_TOKEN: ${{ secrets.WAPM_REGISTRY_TOKEN }}

**Comment by Wakeful-Cloud** [comment]
With the introduction of tokens, the main benefit of this action (Authenticating with username/password) is now largely redundant, however, there is still one benefit: using `run` actions are more fragile than dedicated actions. If/when the WAPM CLI changes, `run` actions may break whereas this action will be updated. Assuming you use a major or minor only version tag, your pipelines will automatically use the updated version of this action.
